### ISSUE TITLE
Contribution License Request for GPTInterviewer Project

### ISSUE THREAD

**Issue by Suraj1089** [jiatastic/GPTInterviewer#1]
Hi jiatastic

I am writing to express my interest in contributing to the GPTInterviewer project. Having a strong background in Python and experience with Streamlit, I believe I can provide meaningful assistance in further developing and improving the functionality of the application. Your project aligns perfectly with my skills and interests, and I would be honored to collaborate with you on its development.

**Comment by jiatastic** [comment]
Hello Suraj,

Absolutely happy if you would like to collaborate and contribute to the project. I'd love to communicate!

**Comment by Suraj1089** [comment]
Hi @jiatastic ,

I am excited to get involved in the GPTInterviewer project. Before I start, could you please add the contribution guidelines and license to the repository? This will help me understand the development process and ensure that I can make meaningful contributions aligned with the project's goals.

**Comment by jiatastic** [comment]
license issued
